### PR TITLE
Server re-querying

### PR DESCRIPTION
**Pull request by TheMagoo73**
Enable re-query of the server if/when either the Token or Cart Data is changed to allow the widgets to work better in Ajax or SPA style checkout flows.

### CODE REVIEW

**Comment by Fletch72** [comment]
Changes look good to me. Test was performed, changing gfs-data and saw the observer re-query checkout.

**Review by mpachnis — CHANGES_REQUESTED** [review]
Code looks good, observer triggered when gfs-data changed. We also need to notify gfs-delivery in case the original delivery has changed.

**Comment by TheMagoo73** [comment]
Have chatted this through with @Fletch72 and we feel that the host site should push address changes to the gfs-delivery widget if it's using it to ensure everything stays consistent. Could be tricky for the Checkout widget to locate the delivery widget, as there's no container. Maybe something for us to pick up in V2 @mpachnis?

**Comment by mpachnis** [comment]
Sounds good to me.

**Comment by TheMagoo73** [comment]
Ok if everyone is happy I'll merge the pull request this afternooon thanks

**Pull request merged**
